# driver pseudo-modules dependencies (in alphabetical order)

ifneq (,$(filter adc%1c,$(USEMODULE)))
  USEMODULE += adcxx1c
endif

ifneq (,$(filter ads101%,$(USEMODULE)))
  USEMODULE += ads101x
endif

ifneq (,$(filter apds99%,$(USEMODULE)))
  USEMODULE += apds99xx
endif

ifneq (,$(filter at24c%,$(USEMODULE)))
  USEMODULE += at24cxxx
endif

ifneq (,$(filter at86rf215%,$(USEMODULE)))
  USEMODULE += at86rf215
endif

ifneq (,$(filter at86rf%, $(filter-out at86rf215%, $(USEMODULE))))
  USEMODULE += at86rf2xx
endif

ifneq (,$(filter bme680_%,$(USEMODULE)))
  USEMODULE += bme680
endif

ifneq (,$(filter bm%280_i2c,$(USEMODULE)))
  USEMODULE += bmx280
endif

ifneq (,$(filter bm%280_spi,$(USEMODULE)))
  USEMODULE += bmx280
endif

ifneq (,$(filter cc110%,$(USEMODULE)))
  USEMODULE += cc110x
endif

ifneq (,$(filter ccs811_%,$(USEMODULE)))
  USEMODULE += ccs811
endif

ifneq (,$(filter ccs811,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio
  FEATURES_REQUIRED += periph_i2c
  USEMODULE += xtimer
endif

ifneq (,$(filter cst816s,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio_irq
  FEATURES_REQUIRED += periph_gpio
  FEATURES_REQUIRED += periph_i2c
  USEMODULE += xtimer
endif

ifneq (,$(filter cst816s,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio_irq
  FEATURES_REQUIRED += periph_gpio
  FEATURES_REQUIRED += periph_i2c
  USEMODULE += xtimer
endif

ifneq (,$(filter cst816s,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio_irq
  FEATURES_REQUIRED += periph_gpio
  FEATURES_REQUIRED += periph_i2c
  USEMODULE += xtimer
endif

ifneq (,$(filter dcf77,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio
  FEATURES_REQUIRED += periph_gpio_irq
  USEMODULE += xtimer
endif

ifneq (,$(filter dht,$(USEMODULE)))
  USEMODULE += xtimer
  FEATURES_REQUIRED += periph_gpio
endif

ifneq (,$(filter ds1307,$(USEMODULE)))
  FEATURES_REQUIRED += periph_i2c
endif

ifneq (,$(filter ds18,$(USEMODULE)))
    USEMODULE += xtimer
    FEATURES_REQUIRED += periph_gpio
endif

ifneq (,$(filter ds3234,$(USEMODULE)))
  FEATURES_REQUIRED += periph_spi
endif

ifneq (,$(filter ds75lx,$(USEMODULE)))
  USEMODULE += xtimer
  FEATURES_REQUIRED += periph_i2c
endif

ifneq (,$(filter dsp0401,$(USEMODULE)))
  USEMODULE += xtimer
  FEATURES_REQUIRED += periph_gpio
  FEATURES_REQUIRED += periph_pwm
endif

ifneq (,$(filter dynamixel,$(USEMODULE)))
  USEMODULE += uart_half_duplex
endif

ifneq (,$(filter enc28j60,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio
  FEATURES_REQUIRED += periph_gpio_irq
  FEATURES_REQUIRED += periph_spi
  USEMODULE += netdev_eth
  USEMODULE += xtimer
  USEMODULE += luid
endif

ifneq (,$(filter encx24j600,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio_irq
  FEATURES_REQUIRED += periph_spi
  USEMODULE += netdev_eth
  USEMODULE += xtimer
endif

ifneq (,$(filter ethos,$(USEMODULE)))
  FEATURES_REQUIRED += periph_uart
  USEMODULE += iolist
  USEMODULE += netdev_eth
  USEMODULE += random
  USEMODULE += tsrb
endif

ifneq (,$(filter dose,$(USEMODULE)))
  FEATURES_REQUIRED += periph_uart
  USEMODULE += iolist
  USEMODULE += netdev_eth
  USEMODULE += random
  USEMODULE += xtimer
  FEATURES_REQUIRED += periph_gpio_irq
endif

ifneq (,$(filter feetech,$(USEMODULE)))
  USEMODULE += uart_half_duplex
endif

ifneq (,$(filter fxos8700,$(USEMODULE)))
  USEMODULE += xtimer
  FEATURES_REQUIRED += periph_i2c
endif

ifneq (,$(filter grove_ledbar,$(USEMODULE)))
  USEMODULE += my9221
endif

ifneq (,$(filter hd44780,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio
  USEMODULE += xtimer
endif

ifneq (,$(filter hdc1000,$(USEMODULE)))
  USEMODULE += xtimer
  FEATURES_REQUIRED += periph_i2c
endif

ifneq (,$(filter hih6130,$(USEMODULE)))
  USEMODULE += xtimer
  FEATURES_REQUIRED += periph_i2c
endif

ifneq (,$(filter hts221,$(USEMODULE)))
  FEATURES_REQUIRED += periph_i2c
endif

ifneq (,$(filter ili9341,$(USEMODULE)))
  FEATURES_REQUIRED += periph_spi
  FEATURES_REQUIRED += periph_gpio
  USEMODULE += xtimer
endif

ifneq (,$(filter ina2%,$(USEMODULE)))
  USEMODULE += ina2xx
endif

ifneq (,$(filter ina3221_%,$(USEMODULE)))
  USEMODULE += ina3221
endif

ifneq (,$(filter itg320x_%,$(USEMODULE)))
  USEMODULE += itg320x
endif

ifneq (,$(filter lis2dh12%,$(USEMODULE)))
  USEMODULE += lis2dh12
endif

ifneq (,$(filter lps331ap lps2%hb,$(USEMODULE)))
  USEMODULE += lpsxxx
endif

ifneq (,$(filter ltc4150_%,$(USEMODULE)))
  USEMODULE += ltc4150
endif

ifneq (,$(filter mcp2515,$(USEMODULE)))
  USEMODULE += xtimer
  FEATURES_REQUIRED += periph_gpio periph_spi periph_gpio_irq
endif

ifneq (,$(filter mhz19_%,$(USEMODULE)))
  USEMODULE += mhz19
endif

ifneq (,$(filter mpu9%50,$(USEMODULE)))
  USEMODULE += mpu9x50
endif

ifneq (,$(filter mrf24j40m%,$(USEMODULE)))
  USEMODULE += mrf24j40
endif

ifneq (,$(filter mtd_%,$(USEMODULE)))
  USEMODULE += mtd
endif

# nrfmin is a concrete module but comes from cpu/nrf5x_common. Due to limitations
# in the dependency resolution mechanism it's not possible to move its
# dependency resolution at cpu level.
ifneq (,$(filter nrfmin,$(USEMODULE)))
  FEATURES_REQUIRED += radio_nrfmin
  FEATURES_REQUIRED += periph_cpuid
  USEMODULE += netif
endif

ifneq (,$(filter periph_ptp_timer periph_ptp_speed_adjustment,$(FEATURES_USED)))
  FEATURES_REQUIRED += periph_ptp
endif

ifneq (,$(filter qmc5883l_%,$(USEMODULE)))
  USEMODULE += qmc5883l
endif

ifneq (,$(filter rn2%3,$(USEMODULE)))
  USEMODULE += rn2xx3
endif

ifneq (,$(filter sdp3x_%,$(USEMODULE)))
  USEMODULE += sdp3x
endif

ifneq (,$(filter sht1%,$(USEMODULE)))
  USEMODULE += sht1x
endif

ifneq (,$(filter si1133,$(USEMODULE)))
  USEMODULE += si1133
endif

ifneq (,$(filter si114%,$(USEMODULE)))
  USEMODULE += si114x
endif

ifneq (,$(filter si70%,$(USEMODULE)))
  USEMODULE += si70xx
endif

ifneq (,$(filter slipdev_%,$(USEMODULE)))
  USEMODULE += slipdev
endif

ifneq (,$(filter sx127%,$(USEMODULE)))
  USEMODULE += sx127x
endif

ifneq (,$(filter tmp00%,$(USEMODULE)))
  USEMODULE += tmp00x
endif

ifneq (,$(filter vcnl40%0,$(USEMODULE)))
  USEMODULE += vcnl40x0
endif

ifneq (,$(filter ws281x_%,$(USEMODULE)))
  USEMODULE += ws281x
endif

ifneq (,$(filter saul_adc,$(USEMODULE)))
  FEATURES_REQUIRED += periph_adc
endif

ifneq (,$(filter saul_gpio,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio
endif

ifneq (,$(filter saul_pwm,$(USEMODULE)))
  FEATURES_REQUIRED += periph_pwm
endif

ifneq (,$(filter saul,$(USEMODULE)))
  USEMODULE += phydat
endif

ifneq (,$(filter saul_nrf_temperature,$(USEMODULE)))
  FEATURES_REQUIRED += periph_temperature
endif

# Enable periph_uart when periph_uart_nonblocking is enabled
ifneq (,$(filter periph_uart_nonblocking,$(USEMODULE)))
  FEATURES_REQUIRED += periph_uart
endif

# Enable periph_gpio when periph_gpio_irq is enabled
ifneq (,$(filter periph_gpio_irq,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio
endif

ifneq (,$(filter periph_timer_periodic,$(USEMODULE)))
  FEATURES_REQUIRED += periph_timer
endif

ifneq (,$(filter netdev_%,$(USEMODULE)))
  USEMODULE += netdev
  # Don't register netdevs if there is only a single one of them
  ifeq (,$(filter gnrc_netif_single,$(USEMODULE)))
    USEMODULE += netdev_register
  endif
  USEMODULE += xtimer
endif

ifneq (,$(filter lis3mdl,$(USEMODULE)))
  FEATURES_REQUIRED += periph_i2c
  USEMODULE += xtimer
endif

ifneq (,$(filter lis3mdl,$(USEMODULE)))
  FEATURES_REQUIRED += periph_i2c
  USEMODULE += xtimer
endif

ifneq (,$(filter xbee,$(USEMODULE)))
  FEATURES_REQUIRED += periph_uart
  FEATURES_REQUIRED += periph_gpio
  USEMODULE += ieee802154
  USEMODULE += xtimer
  USEMODULE += netif
endif

ifneq (,$(filter xpt2046,$(USEMODULE)))
  FEATURES_REQUIRED += periph_gpio
  FEATURES_REQUIRED += periph_gpio_irq
  FEATURES_REQUIRED += periph_spi
endif
